### PR TITLE
📦 NEW: Add support for @wordpress imports

### LINKED ISSUE #27: [FEATURE REQUEST] webpack aliases for Gutenberg components
It would be great to import components from WordPress with @wp alias, like @youknowriad does here:  https://github.com/youknowriad/gcf/blob/master/scripts/blocks/components/field/index.js#L2

Relevant lines in his webpack:
https://github.com/youknowriad/gcf/blob/master/webpack.config.js#L41-L46

### LINKED ISSUE #43: Add webpack aliases for Gutenberg components
It would be great to import components from WordPress with @wp alias, like @youknowriad does here:  https://github.com/youknowriad/gcf/blob/master/scripts/blocks/components/field/index.js#L2

Relevant lines in his webpack:
https://github.com/youknowriad/gcf/blob/master/webpack.config.js#L41-L46

### PR DESCRIPTION
**Pull request by Varstahl**
Improves ahmadawais/clai-old#59, fixes ahmadawais/create-guten-block#43.

This little patch provides support for the `import { … } from '@wordpress/…';` syntax. Tested on Win7 x64 with WordPress 3.9.6 and a slightly modified Columns block straight out of the Gutenberg github. Node 10.2.1, npm 5.6.0.

The main difference from the Gutenberg and the GCF exports, is that the syntax `externals["@wordpress/" + wpDependency] = { this: ["wp", wpDependency] };` would result in a lot of undefined errors at runtime, while `externals[ '@wordpress/${ name }' ] = 'wp.' + wpDependency` works as intended. Both compile equally fine, though.

An excerpt from the source I used for the component and a screen of it showing in the editor:

```js
edit( { attributes, setAttributes, className } ) {
  const { columns } = attributes;
  const classes = classnames( className, `has-${ columns }-columns` );

  return (
    <Fragment>
      <InspectorControls>
        <PanelBody>
          <RangeControl
            label={ __( 'Columns' ) }
            value={ columns }
            onChange={ ( nextColumns ) => {
              setAttributes( {
                columns: nextColumns,
              } );
            } }
            min={ 1 }
            max={ 6 }
          />
        </PanelBody>
      </InspectorControls>
      <div className={ classes }>
        <InnerBlocks layouts={ getColumnLayouts } />
      </div>
    </Fragment>
  );
},

save( { attributes } ) {
  const { columns } = attributes;

  return (
    <div className={ `has-${ columns }-columns` }>
      <InnerBlocks.Content />
    </div>
  );
},
```

Component

### CODE REVIEW

**Comment by ahmadawais** [comment]
Thanks for the contribution @Varstahl since I am traveling, I am paging a friend @richtabor do you have time to review this PR? 

CC: @asharirfan

**Comment by jolidog** [comment]
@Varstahl  This is working great and it's a much needed feature. Only thing it needs to be updated since
```
ga: 'ga', // Old Google Analytics.
gtag: 'gtag', // New Google Analytics.
jquery: 'jQuery', // import $ from 'jquery' // Use the WordPress version.
```

Were added to `packages/cgb-scripts/config/webpack.config.dev.js` in the mean time. Not sure why they are not on the prod version.

**Comment by Varstahl** [comment]
Fixed the merge conflict and updated `webpack.config.prod.js`. Also, thanks @jolidog for the tip. I've switched to other projects since then and without you writing I would have never noticed :D

**Comment by ahmadawais** [comment]
This was added in a different way without so much repetition take a look https://github.com/ahmadawais/create-guten-block/blob/master/CHANGELOG.md

Thanks anyways 👍

**Pull request closed without merging**
