### PR TITLE
👌 IMPROVE: Code documentation — FIX #45

### LINKED ISSUE #45: Why is my eslint throwing this
I've checked my eslint, uninstalled and reinstalled it but whenever I create a new block I get this.

**Missing JSDoc @returns for function. (valid-jsdoc)**

### PR DESCRIPTION
**Pull request by asharirfan**
Hey 🙌

I have added `@return` and `@props` documentation tags to `block.js` file to remove ESLint errors 💯 

## Before screenshot
alt text

## After screenshot
alt text

Cheers!

### CODE REVIEW

**Comment by ahmadawais** [comment]
Thanks @asharirfan for fixing that. Welcome as a contributor.

**Comment by asharirfan** [comment]
You're welcome 🙂
Looking forward to much more 💯

**Comment by HasnainAshfaq** [comment]
I created a block just yesterday. Should I not get the updated block with return and props tag? Mine still has linting problems.

**Comment by ahmadawais** [comment]
The new release with the fix has not been released yet

**Pull request merged**
