### PR TITLE
👌 IMPROVE: Update commented-out lines for versioning assets to refere…

### PR DESCRIPTION
**Pull request by kellenmace**
…nce the assets in the /dist/ directory that are currently being enqueued

### CODE REVIEW

**Review by ahmadawais — COMMENTED** [review]
Looks good to me! 🔥

@asharirfan can you check it for me?!

**Comment by kellenmace** [comment]
I'm using `__DIR__` here, but please let me know if PHP support for the project needs to go all the way down to 5.2, and it can be replaced with `dirname( __FILE__ )` instead.

PHP version usage percentages for reference: https://api.wordpress.org/stats/php/1.0/

**Comment by asharirfan** [comment]
Sure @ahmadawais! Let me get back to you real quick ⚡️

**Comment by asharirfan** [comment]
@ahmadawais PR is looking good 👌

**Comment by ahmadawais** [comment]
Merged! 👋
Welcome @kellenmace as a contributor.

**Pull request merged**
