### PR TITLE
Remove unnecessary parentheses.

### PR DESCRIPTION
**Pull request by tfrommen**
`require_once` is a PHP language construct, and thus [does **not** require any parentheses](https://tfrommen.de/on-php-language-constructs-and-parentheses/). 😉

### CODE REVIEW

**Comment by JulienMelissas** [comment]
TIL ☝️

**Comment by ahmadawais** [comment]
📖 OK, this is a new one for me. Definitely TIL. But what does WordPress standards say about that?
I think that we should keep using the brackets since the WordPress core uses it. Also because in the standards using brackets is said to be a good thing. 

🛠 E.g. even in one line `if` statements standards tell us to use the brackets.

And now, I almost feel bad about crushing the second PR from @tfrommen today. That's not normally how I do #OpenSource 📦 

Thoughts? 🤔

**Comment by ahmadawais** [comment]
Reading your post now.

**Comment by tfrommen** [comment]
Well, to be honest, a lot of things in _WordPress_ are not how you would do them (today). 😉 

That being said, the official WordPress Coding Standards have [included](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/f6ba702bbbb70f793d911b3168142eeb205a7aab/WordPress-Extra/ruleset.xml#L44) a [sniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/src/Standards/PEAR/Sniffs/Files/IncludingFileSniff.php) for this a while back already. When (or **if**) WordPress itself will get adapted, ... we will see.

**Comment by ahmadawais** [comment]
Thank you, for pointing that out, let me read a bit about it tomorrow then I'll probably merge this one. Looks a bit weird to me for now. As you can imagine it should? I do understand the reasoning here. 

Peace! ✌️

**Comment by ahmadawais** [comment]
Thanks for the PR @tfrommen looking forward to more contributions from your end. I decided to go your way :)

**Comment by raajtram** [comment]
@shelob9 has some [related notes](https://torquemag.io/2018/01/dont-follow-wordpress-coding-standards/.) about this as well.

**Pull request merged**
