### PR TITLE
📦 NEW: webpack 4 package updates

### PR DESCRIPTION
**Pull request by asharirfan**
Hi 👋 

I am creating this PR as a module for ahmadawais/create-guten-block#33, and in it, I have updated the webpack from version _3.1.0_ to _4.29.6_

Screenshots
====
Here are the GIF and screenshot of my tests:

image

image

### CODE REVIEW

**Comment by KenEucker** [comment]
@asharirfan I merged in this update but it looks like you reverted the work pertaining to this PR. Is that right?

I put those changes back in, added the babel preset I was needing for my project, and things compiled successfully. I'm going to move on to updating to @babel/core now on my branch.

**Comment by asharirfan** [comment]
Hey @KenEucker 

> I merged in this update but it looks like you reverted the work pertaining to this PR. Is that right?

I am not sure what you're talking about.

I should have closed this PR because I am working on the webpack 4 updates on this branch right now: https://github.com/ahmadawais/create-guten-block/commits/asharirfan/webpack-4

Also, I am testing the integration of `mini-css-extract-plugin` for now and haven't gotten around to @babel/core yet.

Cheers!

**Comment by KenEucker** [comment]
@asharirfan I think what I noticed was on your master branch. I missed the webpack-4 branch.

I also looked into integrating mini-css-extract-plugin as extract-text-webpack-plugin is no longer maintained, but I did not start that work.

Currently creating a webpack 4 + babel 7 PR.

**Comment by ahmadawais** [comment]
@asharirfan you didn't mention what you tested?

- Does the default blocks work?
- The custom blocks work?

**Comment by ahmadawais** [comment]
@asharirfan since you have the npm publish access, kindly have all your PRs include the section with canaray released versions and installation instructions. (We could automate this with GitHub actions if you're up for it).

The following section:

Canary releases for this PR:

```
 - babel-preset-cgb@1.7.0-alpha.acf36ee2
 - cgb-dev-utils@1.6.0-alpha.acf36ee2
 - cgb-scripts@1.18.0-alpha.acf36ee2
 - create-guten-block@1.13.0-alpha.acf36ee2
```

**Comment by ahmadawais** [comment]
@asharirfan when I test your PR this is what I get.



```

❌   Failed to compile.


👉  ./src/blocks.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/ahmadawais/Documents/Web/Dev/Local/local/app/public/wp-content/plugins/cgbwebpackupgrade/node_modules/babel-preset-cgb/index.js
    at Array.map (<anonymous>)
    at Generator.next (<anonymous>)


⠸ Watching for changes... let's fix this... (Press CTRL + C to stop).

```

**Comment by ahmadawais** [comment]
Ok it looks like we need to wait a couple mins since the latest canary was not picked up by npm for some reason.

**Comment by ahmadawais** [comment]
Doesn't work for build and since we are moving away from this I am closing this one.

**Pull request closed without merging**
