### PR TITLE
📦 NEW: webpack 4 package updates

### PR DESCRIPTION
**Pull request by asharirfan**
Updated these packages:

- mini-css-extract-plugin
- webpack-fix-style-only-entries
- webpack
- uglifyjs-webpack-plugin
- style-loader
- sass-loader
- postcss-loader

### CODE REVIEW

**Comment by asharirfan** [comment]
```
- babel-preset-cgb@1.7.0-alpha.e52e47d6
- cgb-dev-utils@1.6.0-alpha.e52e47d6
- cgb-scripts@1.18.0-alpha.e52e47d6
- create-guten-block@1.13.0-alpha.e52e47d6
```

**Comment by ahmadawais** [comment]
```js
import React from 'react';
import styled from 'styled-components';
import rmq from 'styled-rmq';
import Container from './Container';

const Desc = styled.p`
	text-align: center;
	font-family: ${props => props.theme.f2};
	font-size: 2rem;
	font-weight: 400;
	padding: 0;
	margin: 0 auto;

	${rmq('t')} {
		max-width: 63rem;
		padding: 0 1rem;
	}
	${rmq('ml')} {
		font-size: 1.3rem;
		padding: 0 1rem;
	}
`;

export default ({ children }) => (
	<Container>
		<Desc>{children}</Desc>
	</Container>
);
```

**Comment by ahmadawais** [comment]
```js
import React from 'react';
import styled from 'styled-components';
import rmq from 'styled-rmq';
import Container from './Container';

const Wrap = styled.div`
	padding: 8rem 0 0;
	margin: 0 auto;
	max-width: 75rem;
	text-align: center;

	${rmq('ml')} {
		padding: 4rem 0 0;
	}

	&::before {
		content: '';
		position: absolute;
		top: 0px;
		left: 0px;
		width: 100%;
		display: block;
		height: 1px;
		background: linear-gradient(
			to right,
			rgba(227, 231, 235, 0.1) 0px,
			rgba(227, 231, 235, 0.6) 50%,
			rgba(227, 231, 235, 0.1) 100%
		);
	}
`;

const Title = styled.h2`
	font-family: ${props => props.theme.f1};
	font-size: 3.6rem;
	line-height: 1.278;
	letter-spacing: -0.02rem;
	margin-bottom: 1.6rem;

	${rmq('ml')} {
		font-size: 2.5rem;
	}
`;

export default ({ children }) => (
	<Container>
		<Wrap>
			<Title>{children}</Title>
		</Wrap>
	</Container>
);
```

**Comment by asharirfan** [comment]
Latest canary release info:

```
- babel-preset-cgb@1.7.0-alpha.660bdf61
- cgb-dev-utils@1.6.0-alpha.660bdf61
- cgb-scripts@1.18.0-alpha.660bdf61
- create-guten-block@1.13.0-alpha.660bdf61
```

**Comment by asharirfan** [comment]
Latest canary release info:

```
- babel-preset-cgb@1.7.0-alpha.f558514e
- cgb-dev-utils@1.6.0-alpha.f558514e
- cgb-scripts@1.18.0-alpha.f558514e
- create-guten-block@1.13.0-alpha.f558514e
```

**Comment by asharirfan** [comment]
### Canary release info:

```
- babel-preset-cgb@1.7.0-alpha.f558514e
- cgb-dev-utils@1.6.0-alpha.f558514e
- cgb-scripts@1.18.0-alpha.f558514e
- create-guten-block@1.13.0-alpha.f558514e
```

I have implemented [this solution](https://stackoverflow.com/questions/50976979/output-2-or-more-css-files-with-mini-css-extract-plugin-in-webpack?answertab=votes#tab-top) for extracting CSS from webpack 4.

The solution involves the introduction of `file-loader` and `extract-loader`. These two loaders simplify the configs to the point where we can import any amount of `.scss` files in our JS.

I have done the test run by running the following command in the plugins directory of a local WordPress site:

```
npx create-guten-block testing-block -c
```

After activating, running `npm start` in the plugin folder, and editing the plugin these were the results:

### Editor view:

image

### Frontend view:

image

`npm run build` is also running fine.

image

**Review by ahmadawais — CHANGES_REQUESTED** [review]
CSS doesn't work as soon as you have more than one blocks



One block's CSS is loaded and others don't have any.

**Comment by asharirfan** [comment]
## Canary Release Info
```
- babel-preset-cgb@1.7.0-alpha.93524805
- cgb-dev-utils@1.6.0-alpha.93524805
- cgb-scripts@1.18.0-alpha.93524805
- create-guten-block@1.13.0-alpha.93524805
```

I have integrated the `mini-css-extract-plugin` with CGB to extract CSS files with webpack 4. To test this release run the following command:

```
npx create-guten-block@1.13.0-alpha.93524805 -c blockName
```

I have also tested the solution for single and multi-blocks — screenshots to follow.

## Frontend View:
image

image

## Editor View:
image

image

**Pull request closed without merging**
